-- MySQL Script generated by MySQL Workbench
-- Fri Feb  7 20:35:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Date_dim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Date_dim` (
  `DateNum` INT NOT NULL,
  `Date` DATE NOT NULL,
  `YearMonthNum` INT NOT NULL,
  `Calendar_Quarter` TINYTEXT NOT NULL,
  `MonthNum` INT NOT NULL,
  `Month_Name` ENUM('January', 'Feburary', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December') NOT NULL COMMENT '\"',
  `MonthShortName` ENUM('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec') NOT NULL,
  `WeekNum` INT NOT NULL COMMENT '\'1\', \'2\'',
  `DayNumOfYear` INT NOT NULL,
  `DayNumOfMonth` INT NOT NULL,
  `DayNumOfWeek` INT NOT NULL,
  `DayName` ENUM("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday") NOT NULL,
  `DayShortName` ENUM("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun") NOT NULL,
  `Quarter` INT NOT NULL,
  `YearQuarterNum` INT NOT NULL,
  `DayNumOfQuarter` INT NOT NULL,
  `Seaon` ENUM('Autumn', 'Winter', 'Spring', 'Summer') NOT NULL,
  `Year` CHAR(4) NOT NULL COMMENT 'char(4) or Int(4)',
  PRIMARY KEY (`DateNum`),
  INDEX `MonthName_idx` (`Month_Name` ASC) INVISIBLE,
  INDEX `WeekNum_idx` (`WeekNum` ASC) INVISIBLE,
  INDEX `Year_idx` (`Year` ASC) INVISIBLE,
  INDEX `SeasonName_idx` (`Seaon` ASC) INVISIBLE,
  INDEX `QuarterName_idx` (`Quarter` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sales_Agent_Dim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sales_Agent_Dim` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Commision rate` DECIMAL(3,2) NOT NULL,
  `DWSalesAgentID` INT NOT NULL,
  PRIMARY KEY (`DWSalesAgentID`),
  INDEX `AgentID_idx` (`ID` ASC) VISIBLE,
  INDEX `agentName_idx` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Market Dim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Market Dim` (
  `Mkt_ID_Sgt` INT NOT NULL,
  `Mark_Key` TINYTEXT NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Mkt_ID_Sgt`),
  INDEX `Description_idx` (`Description` ASC) VISIBLE,
  INDEX `Mark_key` (`Mark_Key` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer Dim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer Dim` (
  `pk_cust_id` INT NOT NULL,
  `cust_id` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Street Name` VARCHAR(45) NOT NULL,
  `Suburb` VARCHAR(45) BINARY NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `PostCode` VARCHAR(12) NOT NULL,
  `MarketID` TINYTEXT NOT NULL,
  `Changed_date` DATE NULL,
  PRIMARY KEY (`pk_cust_id`),
  INDEX `Cust_naturalKey_idx` (`cust_id` ASC) VISIBLE,
  INDEX `cust_name_idx` (`Name` ASC) VISIBLE,
  INDEX `marketID` (`MarketID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product_Dim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product_Dim` (
  `ProductKey` INT NOT NULL COMMENT 'In propduction system,  \"code\"',
  `ProdYear` CHAR(4) NOT NULL,
  `Price` DECIMAL(7,2) NOT NULL,
  `Volume` INT NOT NULL,
  `Cost` DECIMAL(9,2) NOT NULL,
  `ProdCode` INT NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Group` VARCHAR(45) NOT NULL,
  `DWProdID` INT NOT NULL,
  PRIMARY KEY (`DWProdID`),
  INDEX `ProdKey_idx` (`ProductKey` ASC) INVISIBLE,
  INDEX `ProdCode_idx` (`ProdCode` ASC) INVISIBLE,
  INDEX `Group_idx` (`Group` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transactional_sales_order_fact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transactional_sales_order_fact` (
  `SaleID` INT NOT NULL,
  `LineID` INT NOT NULL,
  `Date_dim_DateNum` INT NOT NULL,
  `Customer Dim_pk_cust_id` INT NOT NULL,
  `Cust_name` VARCHAR(45) NOT NULL,
  `Sales_Agent_DWSalesAgentID` INT NOT NULL,
  `Sale_Agent` VARCHAR(45) NOT NULL,
  `Market Dim_Mkt_ID_Sgt` INT NOT NULL,
  `Product_DWProdID` INT NOT NULL,
  `ProdCode` INT NOT NULL,
  `ProdYear` INT NOT NULL,
  `ProductDescription` VARCHAR(45) NOT NULL,
  `Group` TINYTEXT NOT NULL,
  `unit_sales` INT NOT NULL COMMENT 'SUM(unit_sales)\n',
  `dollar_sales` INT NOT NULL COMMENT 'SUM(dollar_sales)',
  `Total_costs` INT NOT NULL COMMENT 'SUM(costs), costs = cost/doz * unit_sales\n',
  `Margin` INT NOT NULL COMMENT 'SUM(profit = unit_sale * (sale_price/doz -cost_price/doz) - sale_price * commision_rate)',
  `Commision` DECIMAL(9,2) NOT NULL COMMENT 'based on the hugh difference of the commision rates of agents, (e.g, 3% and 19%), we set the datatype to be decimal with flexible number of digits.\nTotal(commision = sale_price * commision_rate) \nper order line.',
  `MonthName` CHAR(10) NOT NULL,
  `WeekNum` INT NOT NULL,
  `SeasonName` CHAR(10) NOT NULL,
  `Quarter` INT NOT NULL,
  `YearQuarterNum` INT NOT NULL,
  PRIMARY KEY (`SaleID`, `LineID`),
  INDEX `fk_DateNum_idx` (`Date_dim_DateNum` ASC) VISIBLE,
  INDEX `fk_AgentID_idx` (`Sales_Agent_DWSalesAgentID` ASC) VISIBLE,
  INDEX `fk_MarketID_idx` (`Market Dim_Mkt_ID_Sgt` ASC) VISIBLE,
  INDEX `fk_custID_idx` (`Customer Dim_pk_cust_id` ASC) VISIBLE,
  INDEX `fk_prodID_idx` (`Product_DWProdID` ASC) INVISIBLE,
  INDEX `ProdCode_idx` (`ProdCode` ASC) INVISIBLE,
  INDEX `MonthName_idx` (`MonthName` ASC) INVISIBLE,
  INDEX `WeekNum_idx` (`WeekNum` ASC) INVISIBLE,
  INDEX `SeasonName_idx` (`SeasonName` ASC) INVISIBLE,
  INDEX `Quarter_idx` () VISIBLE,
  INDEX `QuarterYearNum_idx` (`YearQuarterNum` ASC) VISIBLE,
  CONSTRAINT `fk_Transactional_sales_order_fact_Date_dim1`
    FOREIGN KEY (`Date_dim_DateNum`)
    REFERENCES `mydb`.`Date_dim` (`DateNum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transactional_sales_order_fact_Sales_Agent1`
    FOREIGN KEY (`Sales_Agent_DWSalesAgentID`)
    REFERENCES `mydb`.`Sales_Agent_Dim` (`DWSalesAgentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transactional_sales_order_fact_Market Dim1`
    FOREIGN KEY (`Market Dim_Mkt_ID_Sgt`)
    REFERENCES `mydb`.`Market Dim` (`Mkt_ID_Sgt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transactional_sales_order_fact_Customer Dim1`
    FOREIGN KEY (`Customer Dim_pk_cust_id`)
    REFERENCES `mydb`.`Customer Dim` (`pk_cust_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transactional_sales_order_fact_Product1`
    FOREIGN KEY (`Product_DWProdID`)
    REFERENCES `mydb`.`Product_Dim` (`DWProdID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
